### ISSUE TITLE
Gnome Terminal config missing

### ISSUE THREAD

**Issue by JHurricane96** [ameyrk99/no-mans-sky-rice-i3wm#1]
What do you use to configure the color scheme of your gnome terminal? I tried using pywal, but I don't get the results I see in your screenshot.

**Comment by ameyrk99** [comment]
I'm so sorry I'm replying so late. I didn't look at the issues section. My bad

PyWal didn't work well for me either, so I manually changed the colors in the gnome-terminal. I used the ones in this: https://www.schemecolor.com/no-mans-sky.php 

edit: I added my gnome-terminal profile. Sorry for not doing it before
